### ISSUE TITLE
UNIT ISSUE

### ISSUE THREAD

**Issue by ENMcCool** [ENMcCool/oxrse_unit_conv#1]
### Name (Abbreviation) of the unit you want to create?

Stones to KG

### What is its base SI unit?

KG

### Contributor Guide

- [X] I will comply with the [Contributor Guide](../../CONTRIBUTING.md)

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](../../CODE_OF_CONDUCT.md)

**Comment by kattletka** [comment]
That's a great idea. slay
